#!/usr/bin/env Rscript

# Generate the supplement's source VE table from the exact simulation input.
# This script does not alter estimates or choose additional source seasons.
suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
})

input_path <- "data/processed/cdc_ve_estimates.csv"
bibliography_path <- "references/ve_sources.bib"
output_dir <- "outputs/primary/final_tables"
ve <- read_csv(input_path, show_col_types = FALSE)
groups <- c("all", "6m-8", "9-17", "18-49", "50-64", "65+")
required <- c(
  "season", "season_start_year", "ve_age_group", "ve", "lower_95",
  "upper_95", "citation_key", "source_url", "source_age_group",
  "estimate_status", "source_table"
)
stopifnot(all(required %in% names(ve)), !anyDuplicated(ve[c("season", "ve_age_group")]))
if (any(!ve$ve_age_group %in% groups)) stop("Unexpected VE age stratum.")

bibliography <- readLines(bibliography_path, warn = FALSE)
bib_entries <- grep("^@[A-Za-z]+\\{", bibliography, value = TRUE)
bib_keys <- sub("^@[A-Za-z]+\\{([^,]+),.*$", "\\1", bib_entries)
missing_keys <- setdiff(unique(ve$citation_key), bib_keys)
if (length(missing_keys)) {
  stop("VE citations absent from bibliography: ", paste(missing_keys, collapse = ", "))
}

format_estimate <- function(row) {
  if (nrow(row) == 0L) return("--")
  stopifnot(nrow(row) == 1L)
  sprintf(
    "$%d\\;(%d,\\,%d)$",
    round(100 * row$ve), round(100 * row$lower_95), round(100 * row$upper_95)
  )
}

rows <- vapply(sort(unique(ve$season_start_year)), function(year) {
  season_data <- filter(ve, .data$season_start_year == year)
  cells <- vapply(groups, function(group) {
    format_estimate(filter(season_data, .data$ve_age_group == group))
  }, character(1))
  citations <- paste(unique(season_data$citation_key), collapse = ",")
  paste0(
    unique(season_data$season), " & ", paste(cells, collapse = " & "),
    " & \\citep{", citations, "} \\\\"
  )
}, character(1))

table_lines <- c(
  "% Generated by scripts/build_ve_input_table.R; do not edit values by hand.",
  "\\begin{table}[p]",
  "\\centering",
  "\\caption{Vaccine-effectiveness estimates used in the simulations. Values are reported effectiveness percentages and 95\\% confidence intervals before uncertainty sampling and calibration to the onset of full immune response.}",
  "\\label{tab:ve-inputs}",
  "\\small",
  "\\setlength{\\tabcolsep}{3pt}",
  "\\renewcommand{\\arraystretch}{1.25}",
  "\\begin{tabular}{@{}lccccccc@{}}",
  "\\toprule",
  "Season & All ages & \\shortstack{6 months--8\\\\years} & \\shortstack{9--17\\\\years} & \\shortstack{18--49\\\\years} & \\shortstack{50--64\\\\years} & \\shortstack{$\\geq$65\\\\years} & Source \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\par\\medskip",
  "\\begin{minipage}{\\linewidth}",
  "\\footnotesize",
  "The all-age analyses sampled 12 season-specific estimates; each age-specific analysis sampled 10. Dashes indicate estimates not used in that pool. All rows concern medically attended influenza A or B. The 2024/25 row is a final U.S. Flu VE Network outpatient estimate; the 2025/26 row is preliminary.\\\\[4pt]",
  "Age headings identify the VE pools. Model ages 0--4, 5--24, and 25--49 years use the first three age-specific pools, respectively; model ages 50--64 and $\\geq$65 years use matching pools. For 2010/11, the 6 months--8 years estimate comes from the combined-age result in the article text, and the published 9--49 years estimate supplies both the 9--17 and 18--49 years pools. For 2023/24, the youngest source group is 8 months--8 years. The recent all-age estimates also begin at age 8 months.\\\\[4pt]",
  "For 2015/16, the overall confidence interval is taken from Jackson and colleagues (41--55\\%); the archived CDC page gives a conflicting interval of 43--55\\%. The age-specific values for that season come from the archived CDC table. The companion CSV records the exact source URL, source age group, table location, and publication status for every estimate.",
  "\\end{minipage}",
  "\\end{table}"
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
writeLines(table_lines, file.path(output_dir, "table_s1_ve_inputs.tex"))
if (!file.copy(input_path, file.path(output_dir, "table_s1_ve_inputs.csv"), overwrite = TRUE)) {
  stop("Could not copy the exact VE simulation input.")
}
if (!file.copy(bibliography_path, file.path(output_dir, "ve_sources.bib"), overwrite = TRUE)) {
  stop("Could not copy VE source bibliography.")
}
message("Generated the cited VE input table from ", nrow(ve), " simulation-input rows.")
